<?php

namespace Database\Seeders;

use App\Models\Regency;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class RegencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $regensi = [
            [1, 'Kabupaten Simeulue'],
            [1, 'Kabupaten Aceh Singkil'],
            [1, 'Kabupaten Aceh Selatan'],
            [1, 'Kabupaten Aceh Tenggara'],
            [1, 'Kabupaten Aceh Timur'],
            [1, 'Kabupaten Aceh Tengah'],
            [1, 'Kabupaten Aceh Barat'],
            [1, 'Kabupaten Aceh Besar'],
            [1, 'Kabupaten Pidie'],
            [1, 'Kabupaten Bireuen'],
            [1, 'Kabupaten Aceh Utara'],
            [1, 'Kabupaten Aceh Barat Daya'],
            [1, 'Kabupaten Gayo Lues'],
            [1, 'Kabupaten Aceh Tamiang'],
            [1, 'Kabupaten Nagan Raya'],
            [1, 'Kabupaten Aceh Jaya'],
            [1, 'Kabupaten Bener Meriah'],
            [1, 'Kabupaten Pidie Jaya'],
            [1, 'Kota Banda Aceh'],
            [1, 'Kota Sabang'],
            [1, 'Kota Lhokseumawe'],
            [1, 'Kota Langsa'],
            [1, 'Kota Subulussalam'],
            [2, 'Kabupaten Nias'],
            [2, 'Kabupaten Mandailing Natal'],
            [2, 'Kabupaten Tapanuli Selatan'],
            [2, 'Kabupaten Tapanuli Tengah'],
            [2, 'Kabupaten Tapanuli Utara'],
            [2, 'Kabupaten Toba Samosir'],
            [2, 'Kabupaten Labuhan Batu'],
            [2, 'Kabupaten Asahan'],
            [2, 'Kabupaten Simalungun'],
            [2, 'Kabupaten Dairi'],
            [2, 'Kabupaten Karo'],
            [2, 'Kabupaten Deliserdang'],
            [2, 'Kabupaten Langkat'],
            [2, 'Kabupaten Nias Selatan'],
            [2, 'Kabupaten Humbang Hasundutan'],
            [2, 'Kabupaten Pakpak Bharat'],
            [2, 'Kabupaten Samosir'],
            [2, 'Kabupaten Serdang Bedagai'],
            [2, 'Kabupaten Batu Bara'],
            [2, 'Kabupaten Padang Lawas Utara'],
            [2, 'Kabupaten Padang Lawas'],
            [2, 'Kabupaten Labuhan Batu Selatan'],
            [2, 'Kabupaten Labuhan Batu Utara'],
            [2, 'Kabupaten Nias Utara'],
            [2, 'Kabupaten Nias Barat'],
            [2, 'Kota Sibolga'],
            [2, 'Kota Tanjung Balai'],
            [2, 'Kota Pematang Siantar'],
            [2, 'Kota Tebing Tinggi'],
            [2, 'Kota Medan'],
            [2, 'Kota Binjai'],
            [2, 'Kota Padangsidimpuan'],
            [2, 'Kota Gunungsitoli'],
            [3, 'Kabupaten Kepulauan Mentawai'],
            [3, 'Kabupaten Pesisir Selatan'],
            [3, 'Kabupaten Solok'],
            [3, 'Kabupaten Sijunjung'],
            [3, 'Kabupaten Tanah Datar'],
            [3, 'Kabupaten Padang Pariaman'],
            [3, 'Kabupaten Agam'],
            [3, 'Kabupaten Lima Puluh Kota'],
            [3, 'Kabupaten Pasaman'],
            [3, 'Kabupaten Solok Selatan'],
            [3, 'Kabupaten Dharmasraya'],
            [3, 'Kabupaten Pasaman Barat'],
            [3, 'Kota Padang'],
            [3, 'Kota Solok'],
            [3, 'Kota Sawah Lunto'],
            [3, 'Kota Padang Panjang'],
            [3, 'Kota Bukittinggi'],
            [3, 'Kota Payakumbuh'],
            [3, 'Kota Pariaman'],
            [4, 'Kabupaten Kuantan Singingi'],
            [4, 'Kabupaten Indragiri Hulu'],
            [4, 'Kabupaten Indragiri Hilir'],
            [4, 'Kabupaten Pelalawan'],
            [4, 'Kabupaten S I A K'],
            [4, 'Kabupaten Kampar'],
            [4, 'Kabupaten Rokan Hulu'],
            [4, 'Kabupaten Bengkalis'],
            [4, 'Kabupaten Rokan Hilir'],
            [4, 'Kabupaten Kepulauan Meranti'],
            [4, 'Kota   Pekanbaru'],
            [4, 'Kota Dumai'],
            [5, 'Kabupaten Kerinci'],
            [5, 'Kabupaten Merangin'],
            [5, 'Kabupaten Sarolangun'],
            [5, 'Kabupaten Batang Hari'],
            [5, 'Kabupaten Muaro Jambi'],
            [5, 'Kabupaten Tanjung Jabung Timur'],
            [5, 'Kabupaten Tanjung Jabung Barat'],
            [5, 'Kabupaten Tebo'],
            [5, 'Kabupaten Bungo'],
            [5, 'Kota Jambi'],
            [5, 'Kota Sungai Penuh'],
            [6, 'Kabupaten Ogan Komering Ulu'],
            [6, 'Kabupaten Ogan Komering Ilir'],
            [6, 'Kabupaten Muara Enim'],
            [6, 'Kabupaten Lahat'],
            [6, 'Kabupaten Musi Rawas'],
            [6, 'Kabupaten Musi Banyuasin'],
            [6, 'Kabupaten Banyuasin'],
            [6, 'Kabupaten Ogan Komering Ulu Selatan'],
            [6, 'Kabupaten Ogan Komering Ulu Timur'],
            [6, 'Kabupaten Ogan Ilir'],
            [6, 'Kabupaten Empat Lawang'],
            [6, 'Kabupaten Penukal Abab Lematang Ilir'],
            [6, 'Kabupaten Musi Rawas Utara'],
            [6, 'Kota Palembang'],
            [6, 'Kota Prabumulih'],
            [6, 'Kota Pagar Alam'],
            [6, 'Kota Lubuklinggau'],
            [7, 'Kabupaten Bengkulu Selatan'],
            [7, 'Kabupaten Rejang Lebong'],
            [7, 'Kabupaten Bengkulu Utara'],
            [7, 'Kabupaten Kaur'],
            [7, 'Kabupaten Seluma'],
            [7, 'Kabupaten Mukomuko'],
            [7, 'Kabupaten Lebong'],
            [7, 'Kabupaten Kepahiang'],
            [7, 'Kabupaten Bengkulu Tengah'],
            [7, 'Kota Bengkulu'],
            [8, 'Kabupaten Lampung Barat'],
            [8, 'Kabupaten Tanggamus'],
            [8, 'Kabupaten Lampung Selatan'],
            [8, 'Kabupaten Lampung Timur'],
            [8, 'Kabupaten Lampung Tengah'],
            [8, 'Kabupaten Lampung Utara'],
            [8, 'Kabupaten Way Kanan'],
            [8, 'Kabupaten Tulangbawang'],
            [8, 'Kabupaten Pesawaran'],
            [8, 'Kabupaten Pringsewu'],
            [8, 'Kabupaten Mesuji'],
            [8, 'Kabupaten Tulang Bawang Barat'],
            [8, 'Kabupaten Pesisir Barat'],
            [8, 'Kota Bandar Lampung'],
            [8, 'Kota Metro'],
            [9, 'Kabupaten Bangka'],
            [9, 'Kabupaten Belitung'],
            [9, 'Kabupaten Bangka Barat'],
            [9, 'Kabupaten Bangka Tengah'],
            [9, 'Kabupaten Bangka Selatan'],
            [9, 'Kabupaten Belitung Timur'],
            [9, 'Kota Pangkal Pinang'],
            [10, 'Kabupaten Karimun'],
            [10, 'Kabupaten Bintan'],
            [10, 'Kabupaten Natuna'],
            [10, 'Kabupaten Lingga'],
            [10, 'Kabupaten Kepulauan Anambas'],
            [10, 'Kota Batam'],
            [10, 'Kota Tanjung Pinang'],
            [11, 'Kabupaten Kepulauan Seribu'],
            [11, 'Kota Jakarta Selatan'],
            [11, 'Kota Jakarta Timur'],
            [11, 'Kota Jakarta Pusat'],
            [11, 'Kota Jakarta Barat'],
            [11, 'Kota Jakarta Utara'],
            [12, 'Kabupaten Bogor'],
            [12, 'Kabupaten Sukabumi'],
            [12, 'Kabupaten Cianjur'],
            [12, 'Kabupaten Bandung'],
            [12, 'Kabupaten Garut'],
            [12, 'Kabupaten Tasikmalaya'],
            [12, 'Kabupaten Ciamis'],
            [12, 'Kabupaten Kuningan'],
            [12, 'Kabupaten Cirebon'],
            [12, 'Kabupaten Majalengka'],
            [12, 'Kabupaten Sumedang'],
            [12, 'Kabupaten Indramayu'],
            [12, 'Kabupaten Subang'],
            [12, 'Kabupaten   Purwakarta'],
            [12, 'Kabupaten Karawang'],
            [12, 'Kabupaten Bekasi'],
            [12, 'Kabupaten Bandung Barat'],
            [12, 'Kabupaten Pangandaran'],
            [12, 'Kota Bogor'],
            [12, 'Kota Sukabumi'],
            [12, 'Kota Bandung'],
            [12, 'Kota Cirebon'],
            [12, 'Kota Bekasi'],
            [12, 'Kota Depok'],
            [12, 'Kota Cimahi'],
            [12, 'Kota Tasikmalaya'],
            [12, 'Kota Banjar'],
            [13, 'Kabupaten Cilacap'],
            [13, 'Kabupaten Banyumas'],
            [13, 'Kabupaten Purbalingga'],
            [13, 'Kabupaten Banjarnegara'],
            [13, 'Kabupaten Kebumen'],
            [13, 'Kabupaten Purworejo'],
            [13, 'Kabupaten Wonosobo'],
            [13, 'Kabupaten Magelang'],
            [13, 'Kabupaten Boyolali'],
            [13, 'Kabupaten Klaten'],
            [13, 'Kabupaten Sukoharjo'],
            [13, 'Kabupaten Wonogiri'],
            [13, 'Kabupaten Karanganyar'],
            [13, 'Kabupaten Sragen'],
            [13, 'Kabupaten Grobogan'],
            [13, 'Kabupaten Blora'],
            [13, 'Kabupaten Rembang'],
            [13, 'Kabupaten Pati'],
            [13, 'Kabupaten Kudus'],
            [13, 'Kabupaten Jepara'],
            [13, 'Kabupaten Demak'],
            [13, 'Kabupaten Semarang'],
            [13, 'Kabupaten Temanggung'],
            [13, 'Kabupaten Kendal'],
            [13, 'Kabupaten Batang'],
            [13, 'Kabupaten Pekalongan'],
            [13, 'Kabupaten Pemalang'],
            [13, 'Kabupaten Tegal'],
            [13, 'Kabupaten Brebes'],
            [13, 'Kota Magelang'],
            [13, 'Kota Surakarta'],
            [13, 'Kota Salatiga'],
            [13, 'Kota Semarang'],
            [13, 'Kota Pekalongan'],
            [13, 'Kota   Tegal'],
            [14, 'Kabupaten Kulon Progo'],
            [14, 'Kabupaten Bantul'],
            [14, 'Kabupaten Gunung Kidul'],
            [14, 'Kabupaten Sleman'],
            [14, 'Kota Yogyakarta'],
            [15, 'Kabupaten Pacitan'],
            [15, 'Kabupaten Ponorogo'],
            [15, 'Kabupaten Trenggalek'],
            [15, 'Kabupaten Tulungagung'],
            [15, 'Kabupaten Blitar'],
            [15, 'Kabupaten   Kediri'],
            [15, 'Kabupaten Malang'],
            [15, 'Kabupaten Lumajang'],
            [15, 'Kabupaten Jember'],
            [15, 'Kabupaten Banyuwangi'],
            [15, 'Kabupaten Bondowoso'],
            [15, 'Kabupaten Situbondo'],
            [15, 'Kabupaten Probolinggo'],
            [15, 'Kabupaten Pasuruan'],
            [15, 'Kabupaten Sidoarjo'],
            [15, 'Kabupaten Mojokerto'],
            [15, 'Kabupaten Jombang'],
            [15, 'Kabupaten Nganjuk'],
            [15, 'Kabupaten Madiun'],
            [15, 'Kabupaten Magetan'],
            [15, 'Kabupaten Ngawi'],
            [15, 'Kabupaten Bojonegoro'],
            [15, 'Kabupaten Tuban'],
            [15, 'Kabupaten Lamongan'],
            [15, 'Kabupaten Gresik'],
            [15, 'Kabupaten Bangkalan'],
            [15, 'Kabupaten Sampang'],
            [15, 'Kabupaten Pamekasan'],
            [15, 'Kabupaten Sumenep'],
            [15, 'Kota Kediri'],
            [15, 'Kota Blitar'],
            [15, 'Kota Malang'],
            [15, 'Kota Probolinggo'],
            [15, 'Kota Pasuruan'],
            [15, 'Kota Mojokerto'],
            [15, 'Kota Madiun'],
            [15, 'Kota Surabaya'],
            [15, 'Kota Batu'],
            [16, 'Kabupaten Pandeglang'],
            [16, 'Kabupaten Lebak'],
            [16, 'Kabupaten Tangerang'],
            [16, 'Kabupaten Serang'],
            [16, 'Kota Tangerang'],
            [16, 'Kota Cilegon'],
            [16, 'Kota Serang'],
            [16, 'Kota Tangerang Selatan'],
            [17, 'Kabupaten Jembrana'],
            [17, 'Kabupaten Tabanan'],
            [17, 'Kabupaten Badung'],
            [17, 'Kabupaten Gianyar'],
            [17, 'Kabupaten Klungkung'],
            [17, 'Kabupaten Bangli'],
            [17, 'Kabupaten Karang Asem'],
            [17, 'Kabupaten Buleleng'],
            [17, 'Kota Denpasar'],
            [18, 'Kabupaten Lombok Barat'],
            [18, 'Kabupaten Lombok Tengah'],
            [18, 'Kabupaten Lombok Timur'],
            [18, 'Kabupaten Sumbawa'],
            [18, 'Kabupaten Dompu'],
            [18, 'Kabupaten Bima'],
            [18, 'Kabupaten Sumbawa Barat'],
            [18, 'Kabupaten Lombok Utara'],
            [18, 'Kota Mataram'],
            [18, 'Kota Bima'],
            [19, 'Kabupaten Sumba Barat'],
            [19, 'Kabupaten Sumba Timur'],
            [19, 'Kabupaten Kupang'],
            [19, 'Kabupaten Timor Tengah Selatan'],
            [19, 'Kabupaten Timor Tengah Utara'],
            [19, 'Kabupaten Belu'],
            [19, 'Kabupaten Alor'],
            [19, 'Kabupaten Flores Timur'],
            [19, 'Kabupaten Sikka'],
            [19, 'Kabupaten Ende'],
            [19, 'Kabupaten Ngada'],
            [19, 'Kabupaten Manggarai'],
            [19, 'Kabupaten Rote Ndao'],
            [19, 'Kabupaten Manggarai Barat'],
            [19, 'Kabupaten Sumba Tengah'],
            [19, 'Kabupaten Sumba Barat Daya'],
            [19, 'Kabupaten Nagekeo'],
            [19, 'Kabupaten Manggarai Timur'],
            [19, 'Kabupaten Sabu Raijua'],
            [19, 'Kabupaten Malaka'],
            [19, 'Kota Kupang'],
            [20, 'Kabupaten Sambas'],
            [20, 'Kabupaten Mempawah'],
            [20, 'Kabupaten Sanggau'],
            [20, 'Kabupaten Ketapang'],
            [20, 'Kabupaten Sintang'],
            [20, 'Kabupaten Kapuas Hulu'],
            [20, 'Kabupaten Bengkayang'],
            [20, 'Kabupaten Landak'],
            [20, 'Kabupaten Sekadau'],
            [20, 'Kabupaten Melawi'],
            [20, 'Kabupaten Kayong Utara'],
            [20, 'Kabupaten Kubu Raya'],
            [20, 'Kota Pontianak'],
            [20, 'Kota Singkawang'],
            [21, 'Kabupaten Kotawaringin Barat'],
            [21, 'Kabupaten Kotawaringin Timur'],
            [21, 'Kabupaten Kapuas'],
            [21, 'Kabupaten Barito Selatan'],
            [21, 'Kabupaten Barito Utara'],
            [21, 'Kabupaten Sukamara'],
            [21, 'Kabupaten Lamandau'],
            [21, 'Kabupaten Seruyan'],
            [21, 'Kabupaten Katingan'],
            [21, 'Kabupaten Pulang Pisau'],
            [21, 'Kabupaten Gunung Mas'],
            [21, 'Kabupaten Barito Timur'],
            [21, 'Kabupaten Murung Raya'],
            [21, 'Kota Palangka Raya'],
            [22, 'Kabupaten Tanah Laut'],
            [22, 'Kabupaten Kota Baru'],
            [22, 'Kabupaten Banjar'],
            [22, 'Kabupaten Barito Kuala'],
            [22, 'Kabupaten Tapin'],
            [22, 'Kabupaten Hulu Sungai Selatan'],
            [22, 'Kabupaten Hulu Sungai Tengah'],
            [22, 'Kabupaten Hulu Sungai Utara'],
            [22, 'Kabupaten Tabalong'],
            [22, 'Kabupaten Tanah Bumbu'],
            [22, 'Kabupaten Balangan'],
            [22, 'Kota Banjarmasin'],
            [22, 'Kota Banjarbaru'],
            [23, 'Kabupaten Paser'],
            [23, 'Kabupaten Kutai Barat'],
            [23, 'Kabupaten Kutai Kartanegara'],
            [23, 'Kabupaten Kutai Timur'],
            [23, 'Kabupaten Berau'],
            [23, 'Kabupaten Penajam Paser Utara'],
            [23, 'Kota Balikpapan'],
            [23, 'Kota Samarinda'],
            [23, 'Kota Bontang'],
            [24, 'Kabupaten Malinau'],
            [24, 'Kabupaten Bulungan'],
            [24, 'Kabupaten Tana Tidung'],
            [24, 'Kabupaten Nunukan'],
            [24, 'Kota Tarakan'],
            [25, 'Kabupaten Bolaang Mongondow'],
            [25, 'Kabupaten Minahasa'],
            [25, 'Kabupaten Kepulauan Sangihe'],
            [25, 'Kabupaten Kepulauan Talaud'],
            [25, 'Kabupaten Minahasa Selatan'],
            [25, 'Kabupaten Minahasa Utara'],
            [25, 'Kabupaten Bolaang Mongondow Utara'],
            [25, 'Kabupaten Siau Tagulandang Biaro (Sitaro)'],
            [25, 'Kabupaten Minahasa Tenggara'],
            [25, 'Kabupaten Bolaang Mongondow Selatan'],
            [25, 'Kabupaten Bolaang Mongondow Timur'],
            [25, 'Kota Manado'],
            [25, 'Kota Bitung'],
            [25, 'Kota Tomohon'],
            [25, 'Kota Kotamobagu'],
            [26, 'Kabupaten Banggai'],
            [26, 'Kabupaten Poso'],
            [26, 'Kabupaten Donggala'],
            [26, 'Kabupaten Toli-Toli'],
            [26, 'Kabupaten Buol'],
            [26, 'Kabupaten Morowali'],
            [26, 'Kabupaten Banggai Kepulauan'],
            [26, 'Kabupaten Parigi Moutong'],
            [26, 'Kabupaten Tojo Una-Una'],
            [26, 'Kabupaten Sigi'],
            [26, 'Kota Palu'],
            [27, 'Kabupaten Kepulauan Selayar'],
            [27, 'Kabupaten Bulukumba'],
            [27, 'Kabupaten Bantaeng'],
            [27, 'Kabupaten Jeneponto'],
            [27, 'Kabupaten Takalar'],
            [27, 'Kabupaten Gowa'],
            [27, 'Kabupaten Sinjai'],
            [27, 'Kabupaten Bone'],
            [27, 'Kabupaten Maros'],
            [27, 'Kabupaten Pangkajene Dan Kepulauan'],
            [27, 'Kabupaten Barru'],
            [27, 'Kabupaten Soppeng'],
            [27, 'Kabupaten Wajo'],
            [27, 'Kabupaten Sidenreng Rappang'],
            [27, 'Kabupaten Pinrang'],
            [27, 'Kabupaten Enrekang'],
            [27, 'Kabupaten Luwu'],
            [27, 'Kabupaten Tana Toraja'],
            [27, 'Kabupaten Luwu Utara'],
            [27, 'Kabupaten Luwu Timur'],
            [27, 'Kabupaten Toraja Utara'],
            [27, 'Kota Makassar'],
            [27, 'Kota Parepare'],
            [27, 'Kota Palu'],
            [28, 'Kabupaten Buton'],
            [28, 'Kabupaten Muna'],
            [28, 'Kabupaten Konawe'],
            [28, 'Kabupaten Kolaka'],
            [28, 'Kabupaten Konawe Selatan'],
            [28, 'Kabupaten Bombana'],
            [28, 'Kabupaten Wakatobi'],
            [28, 'Kabupaten Kolaka Utara'],
            [28, 'Kabupaten Buton Utara'],
            [28, 'Kabupaten Konawe Utara'],
            [28, 'Kabupaten Kolaka Timur'],
            [28, 'Kabupaten Konawe Kepulauan'],
            [28, 'Kabupaten Muna Barat'],
            [28, 'Kabupaten Buton Tengah'],
            [28, 'Kabupaten Buton Selatan'],
            [28, 'Kota Kendari'],
            [28, 'Kota Baubau'],
            [29, 'Kabupaten Boalemo'],
            [29, 'Kabupaten Gorontalo'],
            [29, 'Kabupaten Pohuwato'],
            [29, 'Kabupaten Bone Bolango'],
            [29, 'Kabupaten Gorontalo Utara'],
            [29, 'Kota Gorontalo'],
            [30, 'Kabupaten Majene'],
            [30, 'Kabupaten Polewali Mandar'],
            [30, 'Kabupaten Mamasa'],
            [30, 'Kabupaten Mamuju'],
            [30, 'Kabupaten Mamuju Utara'],
            [30, 'Kabupaten Mamuju Tengah'],
            [31, 'Kabupaten Maluku Tenggara Barat'],
            [31, 'Kabupaten Maluku Tenggara'],
            [31, 'Kabupaten Maluku Tengah'],
            [31, 'Kabupaten Buru'],
            [31, 'Kabupaten Kepulauan Aru'],
            [31, 'Kabupaten Seram Bagian Barat'],
            [31, 'Kabupaten Seram Bagian Timur'],
            [31, 'Kabupaten Maluku Barat Daya'],
            [31, 'Kabupaten Buru Selatan'],
            [31, 'Kota Ambon'],
            [31, 'Kota Tual'],
            [32, 'Kabupaten Halmahera Barat'],
            [32, 'Kabupaten Halmahera Tengah'],
            [32, 'Kabupaten Kepulauan Sula'],
            [32, 'Kabupaten Halmahera Selatan'],
            [32, 'Kabupaten Halmahera Utara'],
            [32, 'Kabupaten Halmahera Timur'],
            [32, 'Kabupaten Pulau Morotai'],
            [32, 'Kabupaten Pulau Taliabu'],
            [32, 'Kota Ternate'],
            [32, 'Kota Tidore Kepulauan'],
            [33, 'Kabupaten Sarmi'],
            [33, 'Kabupaten Keerom'],
            [33, 'Kabupaten Waropen'],
            [33, 'Kabupaten Supiori'],
            [33, 'Kabupaten Mamberamo Raya'],
            [33, 'Kota Jayapura'],
            [34, 'Kabupaten Fakfak'],
            [34, 'Kabupaten Kaimana'],
            [34, 'Kabupaten Teluk Wondama'],
            [34, 'Kabupaten Teluk Bintuni'],
            [34, 'Kabupaten Manokwari'],
            [34, 'Kabupaten Sorong Selatan'],
            [34, 'Kabupaten Sorong'],
            [34, 'Kabupaten Raja Ampat'],
            [34, 'Kabupaten Tambrauw'],
            [34, 'Kabupaten Maybrat'],
            [34, 'Kabupaten Manokwari Selatan'],
            [34, 'Kabupaten Pegunungan Arfak'],
            [34, 'Kota Sorong'],
            [35, 'Kabupaten Asmat'],
            [35, 'Kabupaten Boven Digoel'],
            [35, 'Kabupaten Mappi'],
            [35, 'Kabupaten Merauke'],
            [36, 'Kabupaten Deiyai (Deliyai)'],
            [36, 'Kabupaten Dogiyai'],
            [36, 'Kabupaten Intan Jaya'],
            [36, 'Kabupaten Mimika'],
            [36, 'Kabupaten Nabire'],
            [36, 'Kabupaten Paniai'],
            [36, 'Kabupaten Puncak'],
            [36, 'Kabupaten Puncak Jaya'],
            [37, 'Kabupaten Jayawijaya'],
            [37, 'Kabupaten Lanny Jaya'],
            [37, 'Kabupaten Mamberamo Tengah'],
            [37, 'Kabupaten Nduga'],
            [37, 'Kabupaten Pegunungan Bintang'],
            [37, 'Kabupaten Tolikara'],
            [37, 'Kabupaten Yahukimo'],
            [37, 'Kabupaten Yalimo'],
            [38, 'Kabupaten Maybrat'],
            [38, 'Kabupaten Raja Ampat'],
            [38, 'Kabupaten Sorong'],
            [38, 'Kabupaten Sorong Selatan'],
            [38, 'Kabupaten Tambrauw'],
            [38, 'Kota Sorong'],
        ];

        foreach ($regensi as [$province_id, $name]) {
            Regency::create([
                'province_id' => $province_id,
                'name' => $name,
            ]);
        }
    }
}
